# Generated by Django 5.0.7 on 2024-08-20 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='branch',
            new_name='branch_name',
        ),
    ]
