# Generated by Django 5.0.7 on 2024-08-20 07:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_rename_branch_user_branch_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.store'),
        ),
    ]
